server:
  port: 8081

spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888

# For Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
